keys:
  - &users:
    - &jmcelroy-dev age1x69ly0nnv0dn8cndeaufuvja6ya94qk8c8y8p6fxv83jceekravqygdqdl
  - &hosts:
    - &earth age1aye39eg23jwlwu3v6j0vrye5ypf68tspnp0unardvmyna744sulqljjexf
    - &mars age1uuz0w0sd5ka5xc4m6sadldfpfagwz0aps823paq7l89p8kdsd9wsdrmrxf
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *jmcelroy-dev
      - *earth
      - *mars