wifi_password: ENC[AES256_GCM,data:0nnWvIxoNRCGWHx71WWcjP04vKj+pJ4=,iv:KmF2JjvsQI44ASVoGRJPvdhiReNK0vR/029gq7O9JM4=,tag:ixSWRTDnvQXdULn5ezqPXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x69ly0nnv0dn8cndeaufuvja6ya94qk8c8y8p6fxv83jceekravqygdqdl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGd1hPeFhPMm1KcHJvNmFl
            VmdwRVhETGJTL2IxeDVBT2JvSm9JWkRodUFzCjFrajB3R1ZtZG11SGdobEdDNVNG
            SHUzbUc4Q0ppdjdSUG5mQnd1S3Y3WWsKLS0tIHNBelUvT0Z5NXp3V3Bmbnhjb0lv
            U2RFbk1SMG1rUDhmdzl5YTJvS0JCMFEKhS6Dvd5RWAX/asMO5JI+cUy/nF5shsdP
            9rwaoPTt3CY3WU5vvYT2wDxMDPFec+CYQm0UfIqncc/H3sQzgF4X6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aye39eg23jwlwu3v6j0vrye5ypf68tspnp0unardvmyna744sulqljjexf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWWdhK3ZSTUV2ZFl5V1o0
            M2xvWXRIaWJSU1ZGQlM3TE9CdW9mbmRlSW1nCjdtQjN1KzAyc3FWdVVWdUJDSTd1
            QUQxeDhKRzYxNXcyZVNncG9vVnVROTAKLS0tIFoxdllkd0ViMjBjdE5IdU1naHVp
            aEVIMXV6RUJZemVjcXdxM0daR1NmK1EKV5MNbcfWZo1w28iH9IDhrR16zFQtv3dM
            MMtQhdcyUeFScGa9YJgeDgJteXnYtRpy21nvhddiAKmv38CNzf2s0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uuz0w0sd5ka5xc4m6sadldfpfagwz0aps823paq7l89p8kdsd9wsdrmrxf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR0U3ejRHQmtRTTVrbW5K
            TEVxenBiWTQxOTh2SXREZ3NWOGpPMDcxbERFCmtJQkZ0Zy93QWlKb2RvWDhuc1U1
            M2hUd0txQ2t5OWh5MmRZQXJYTzVXTjAKLS0tIC9rR0tjQVNkWkpDTCthTlgyUDY5
            VC94aVpzUENudEJ3bHNha2dkc1hIL1EKiNDwXkPs6nn3ixaS2jm73znT1f7efZDI
            2GX4CkbmewbtiF0SHYdVI57baNfA7sG/UGe82iBriWQ47q5rMfRpIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-26T20:25:17Z"
    mac: ENC[AES256_GCM,data:UB3ieCFmX2CRo6aXjTqyUICSkBP+5dQ3RDwlJDMmrzQciwXYWd+BW4u0TdQlERBwB8vJybxgGdpbid8XuosVZrdG17o5MSjlHipuVy5xcwcgms2su8Ku66MD1uwxTQkl7WTsH0NADBCHyPetbkMSYjazWzSduNfK/udySBiewpg=,iv:5A6KnJMsA4O7kddGcI2R/UwNrvZBGpvv7oeqxmwSxxI=,tag:Hj6ymxp3PT++P07GUzJ2CQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
