# Configures the routers
- name: Configure OpenWRT Router
  hosts: router
  gather_facts: false
  vars:
    secrets: "{{ lookup('community.sops.sops', 'sops_secrets.yaml') | from_yaml }}"
    wifi_password: "{{ secrets.wifi_password }}"

    wifi_devices:
      - name: wireless.radio0
        band: '5g'
        channel: '36'
      - name: wireless.radio1
        band: '2g'
        channel: '1'
    wifi_interfaces:
      - name: wireless.default_radio0
        device: 'radio0'
      - name: wireless.default_radio1
        device: 'radio1'
  roles:
    - role: gekmihesg.openwrt
  tasks:
    - name: Ensure required packages are installed
      community.general.opkg:
        name: "{{ item }}"
        state: present
      loop:
        - luci
        - luci-app-firewall
        - wireguard-tools

    - name: Configure WAN
      uci:
        command: set
        key: network.wan
        value:
          peerdns: '0'
          dns:
            - "{{ hostvars['mars']['ansible_host'] }}"

    ############################################################################
    ### VLANs
    ############################################################################

    - name: Configure switch
      uci:
        command: section
        config: network
        type: switch
        name: switch0
        find:
          name: switch0
        value:
          reset: '1'
          enable_vlan: '1'

    - name: Configure non-vpn VLAN
      uci:
        command: section
        config: network
        type: switch_vlan
        name: nonvpn_vlan
        find:
          device: switch0
          vlan: 1
        value:
          ports: '2 3 4 5 0t'

    - name: Configure wan VLAN
      uci:
        command: section
        config: network
        type: switch_vlan
        name: wan_vlan
        find:
          device: switch0
          vlan: 2
        value:
          ports: '1 0t'
    
    - name: Configure vpn VLAN
      uci:
        command: section
        config: network
        type: switch_vlan
        name: vpn_vlan
        find:
          device: switch0
          vlan: 3
        value:
          ports: '2t 3t 4t 5t 0t'

    ############################################################################
    ### Devices
    ############################################################################

    - name: Configure non-vpn lan bridge device
      uci:
        command: section
        config: network
        type: device
        name: br_lan
        find:
          name: br-lan
        value:
          type: bridge
          ports: eth0.1

    - name: Configure vpn lan bridge device
      uci:
        command: section
        config: network
        type: device
        name: br_vpn
        find:
          name: br-vpn
        value:
          type: bridge
          ports: eth0.3

    ############################################################################
    ### Interfaces
    ############################################################################

    - name: Configure non-VPN interface
      uci:
        command: section
        config: network
        type: interface
        name: lan
        find:
          device: br-lan
        value:
          proto: static
          ip6assign: '60'
          ipaddr:
            - '192.168.1.1/24'
            - '192.168.0.1/24'

    - name: Configure VPN interface
      uci:
        command: section
        config: network
        type: interface
        name: vpn
        find:
          device: br-vpn
        value:
          proto: static
          ip6assign: '60'
          ipaddr:
            - '192.168.3.1/24'

    ############################################################################
    ### Wifi
    ############################################################################

    - name: Configure wifi device
      uci:
        command: set
        key: "{{ wifi.name }}"
        value:
          type: 'mac80211'
          band: "{{ wifi.band }}"
          channel: "{{ wifi.channel }}"
          disabled: '0'
      loop: "{{ wifi_devices }}"
      loop_control:
        loop_var: wifi
        label: "{{ wifi.name }}"

    - name: Configure wifi interface
      uci:
        command: set
        key: "{{ wifi.name }}"
        value:
          device: "{{ wifi.device }}"
          network: 'lan'
          mode: 'ap'
          ssid: '@xxxx[]::::::::::::::::::::::::>'
          encryption: 'psk2'
          disabled: '0'
      loop: "{{ wifi_interfaces }}"
      loop_control:
        loop_var: wifi
        label: "{{ wifi.name }}"

    - name: Set wifi password
      uci:
        command: set
        key: "{{ wifi.name }}"
        value:
          key: "{{ wifi_password }}"
      loop: "{{ wifi_interfaces }}"
      loop_control:
        loop_var: wifi
        label: "{{ wifi.name }}"
      no_log: true

    ############################################################################
    ### Firewall
    ############################################################################

    - name: Configure lan firewall zone
      uci:
        command: section
        config: firewall
        type: zone
        name: lan
        find:
          name: lan
          network: lan
        value:
          input: ACCEPT
          output: ACCEPT
          forward: ACCEPT

    - name: Configure wan firewall zone
      uci:
        command: section
        config: firewall
        type: zone
        name: wan
        find:
          name: wan
          network:
            - wan
            - wan6
        value:
          input: REJECT
          output: ACCEPT
          forward: REJECT
          masq: 1
          mtu_fix: 1

    - name: Configure vpn firewall zone
      uci:
        command: section
        config: firewall
        type: zone
        name: vpn
        find:
          name: vpn
          network: vpn
        value:
          input: ACCEPT
          output: ACCEPT
          forward: ACCEPT  

    ############################################################################
    ### Commit changes
    ############################################################################

    - name: Commit UCI changes
      when: not (no_commit | default(false) | bool)
      uci:
        command: commit
      notify: reload wifi
