# Configures the routers
- name: Configure OpenWRT Router
  hosts: router
  gather_facts: false
  vars:
    secrets: "{{ lookup('community.sops.sops', 'sops_secrets.yaml') | from_yaml }}"
    wifi_password: "{{ secrets.wifi_password }}"

    wifi_devices:
      - name: wireless.radio0
        band: '5g'
        channel: '36'
      - name: wireless.radio1
        band: '2g'
        channel: '1'
    wifi_interfaces:
      - name: wireless.default_radio0
        device: 'radio0'
      - name: wireless.default_radio1
        device: 'radio1'
  roles:
    - role: gekmihesg.openwrt
  tasks:
    - name: Ensure required packages are installed
      community.general.opkg:
        name: "{{ item }}"
        state: present
      loop:
        - luci
        - luci-app-firewall
        - wireguard-tools

    - name: Configure WAN
      uci:
        command: set
        key: network.wan
        value:
          peerdns: '0'
          dns:
            - "{{ hostvars['mars']['ansible_host'] }}"

    ############################################################################
    ### VLANs
    ############################################################################

    - name: Ensure that VLAN1 exists
      block:
        - name: Get VLAN1
          uci:
            command: get
            key: network.@switch_vlan[0]
          register: vlan1_exists
      rescue:
        - name: Add VLAN 1 if it doesn't exist
          uci:
            command: add
            key: network.switch_vlan
          when: "vlan1_exists.result == 'uci: Entry not found'"

    - name: Configure VLAN 1 (non-vpn LAN)
      uci:
        command: set
        key: network.@switch_vlan[0]
        value:
          device: 'switch0'
          vlan: '1'
          ports: '2 3 4 5 0t'

    - name: Ensure that VLAN2 exists
      block:
        - name: Get VLAN2
          uci:
            command: get
            key: network.@switch_vlan[1]
          register: vlan2_exists
      rescue:
        - name: Add VLAN 2 if it doesn't exist
          uci:
            command: add
            key: network.switch_vlan
          when: "vlan2_exists.result == 'uci: Entry not found'"

    - name: Configure VLAN 2 (WAN)
      uci:
        command: set
        key: network.@switch_vlan[1]
        value:
          device: 'switch0'
          vlan: '2'
          ports: '1 0t'
    
    - name: Ensure that VLAN3 exists
      block:
        - name: Get VLAN3
          uci:
            command: get
            key: network.@switch_vlan[2]
          register: vlan3_exists
      rescue:
        - name: Add VLAN 3 if it doesn't exist
          uci:
            command: add
            key: network.switch_vlan
          when: "vlan3_exists.result == 'uci: Entry not found'"

    - name: Configure VLAN 3 (VPN LAN)
      uci:
        command: set
        key: network.@switch_vlan[2]
        value:
          device: 'switch0'
          vlan: '3'
          ports: '2t 3t 4t 5t 0t'

    ############################################################################
    ### Devices
    ############################################################################

    - name: Ensure that device 1 exists
      block:
        - name: Get device 1
          uci:
            command: get
            key: network.@device[0]
          register: device0_exists
      rescue:
        - name: Add device 1 if it doesn't exist
          uci:
            command: add
            key: network.device
          when: "device0_exists.result == 'uci: Entry not found'"

    - name: Configure non-vpn lan bridge device
      uci:
        command: set
        key: network.@device[0]
        value:
          name: 'br-lan'
          type: 'bridge'
          ports: 'eth0.1'

    - name: Ensure that device 3 exists
      block:
        - name: Get device 3
          uci:
            command: get
            key: network.@device[2]
          register: device2_exists
      rescue:
        - name: Add device 3 if it doesn't exist
          uci:
            command: add
            key: network.device
          when: "device2_exists.result == 'uci: Entry not found'"

    - name: Configure vpn lan bridge device
      uci:
        command: set
        key: network.@device[2]
        value:
          name: 'br-vpn'
          type: 'bridge'
          ports: 'eth0.3'

    ############################################################################
    ### Interfaces
    ############################################################################

    # - name: Configure non-VPN interface
    #   uci:
    #     command: set
    #     key: network.lan
    #     value:
    #       device: 'br-lan'
    #       proto: 'static'
    #       ip6assign: '60'
    #       ipaddr:
    #         - '192.168.1.1/24'
    #         - '192.168.0.1/24'

    - name: Create VPN interface
      uci:
        command: set
        key: network.vpn
        value: interface

    - name: Configure VPN interface
      uci:
        command: set  
        key: network.vpn
        value:
          device: 'eth0.3'
          proto: 'static'
          ip6assign: '60'
          ipaddr:
            - '192.168.3.1/24'

    ############################################################################
    ### Wifi
    ############################################################################

    - name: Configure wifi device
      uci:
        command: set
        key: "{{ wifi.name }}"
        value:
          type: 'mac80211'
          band: "{{ wifi.band }}"
          channel: "{{ wifi.channel }}"
          disabled: '0'
      loop: "{{ wifi_devices }}"
      loop_control:
        loop_var: wifi
        label: "{{ wifi.name }}"

    - name: Configure wifi interface
      uci:
        command: set
        key: "{{ wifi.name }}"
        value:
          device: "{{ wifi.device }}"
          network: 'lan'
          mode: 'ap'
          ssid: '@xxxx[]::::::::::::::::::::::::>'
          encryption: 'psk2'
          disabled: '0'
      loop: "{{ wifi_interfaces }}"
      loop_control:
        loop_var: wifi
        label: "{{ wifi.name }}"

    - name: Set wifi password
      uci:
        command: set
        key: "{{ wifi.name }}"
        value:
          key: "{{ wifi_password }}"
      loop: "{{ wifi_interfaces }}"
      loop_control:
        loop_var: wifi
        label: "{{ wifi.name }}"
      no_log: true

    ############################################################################
    ### Commit changes
    ############################################################################

    - name: Commit UCI changes
      uci:
        command: commit
      notify: reload wifi
