apiVersion: 1
groups:
    - orgId: 1
      name: Realtime
      folder: SystemDown
      interval: 1m
      rules:
        - uid: eegne5tszek1sd
          title: ServerDown
          condition: down_status
          data:
            - refId: up_status
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                expr: up * on (instance) group_left(role) role{role="critical"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: up_status
            - refId: down_status
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 1
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - down_status
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: up_status
                intervalMs: 1000
                maxDataPoints: 43200
                refId: down_status
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          annotations:
            summary: 'System is down: {{ $labels.instance }}'
          labels: {}
          isPaused: false
          notification_settings:
            receiver: Discord
