name: Production deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ssh
        echo "$SSH_KEY" > ssh/id_rsa
        chmod 600 ssh/id_rsa
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
    
    - name: Deploy to all hosts
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ssh/id_rsa
        nix run .#deploy-all
        ssh-agent -k