name: Nix Check

on:
  push:

jobs:
  nix-check:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Nix Check
      run: nix flake check