name: Test deployment

concurrency: testing

on:
  push:
    branches:
      - develop

jobs:
  deployment:
    runs-on: self-hosted
    environment: testing

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ssh
        echo "$SSH_KEY" > ssh/id_rsa
        chmod 600 ssh/id_rsa
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
    
    - name: Deploy to mars
      env:
        SSH_KEY_PASSWORD: ${{ secrets.SSH_KEY_PASSWORD }}  
      run: |
        eval "$(ssh-agent -s)"
        echo "$SSH_KEY_PASSWORD" | ssh-add ssh/id_rsa
        nix run .#test-deploy mars
        ssh-agent -k