name: Test deployment

concurrency: testing

on:
  push:
    branches:
      - develop

jobs:
  deployment:
    runs-on: self-hosted
    environment: testing

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ssh
        echo "$SSH_KEY" > ssh/id_rsa
        chmod 600 ssh/id_rsa
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
    
    - name: Test deployment to all hosts
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ssh/id_rsa
        nix run .#test-deploy-all
        ssh-agent -k